---
title: "R Notebook"
output: html_notebook
---


```{r}
#LOAD
pacman::p_load(readxl,tidyverse,ggpubr,devtools,plotly,tmap,tmaptools)
#dane <- read_excel("gospodarstwa.xls")
#gry <- read.csv("vgsales-12-4-2019-short.csv")
#df <- read.csv("https://raw.githubusercontent.com/plotly/datasets/master/2014_world_gdp_with_codes.csv")
```

```{r} 
#GGPUBR LEARN
ggplot(dane, aes(wydg,dochg)) +
  geom_point() +
  geom_smooth(method = lm) +
  stat_cor(method = "pearson", label.x = 20)
```

```{r}
ggboxplot(dane,x="woj", y="dochg",
          title = "Polish lands and expenses",
          color="woj",palette = "rainbow")

ggboxplot(dane,x="woj",
          y=c("dochg","wydg","d36"),
          title=c("dochg","wydg","d36"),
          ylab="Expression",
          color="woj",palette = "rainbow")

ggdensity(dane,
       x = c("trb", "klm",  "d36"),
       y = "..density..",
       combine = TRUE,                
       xlab = "Expression", 
       add = "median",                  
       rug = TRUE) 

ggdensity(dane,
       x = c("wydg", "dochg"),
       y = "..count..",
       color =".x.", fill = ".x.",
       facet.by = "woj",
       merge = TRUE,          
       xlab = "Expression",
       add = "median",                
       rug = TRUE ,                 
       palette = "jco"                  
)
```

```{r}
#PLOTLY LEARN

fig <- plot_ly(dane, x=~woj,y=~klm,z=~dochg,color=~woj)
fig <- fig <- fig %>% layout(
    title = "Earnings grouped by lands and type of city",
    scene = list(
      xaxis = list(title = "Lands"),
      yaxis = list(title = "Type of city"),
      zaxis = list(title = "Earnings")
    ))
fig

plot_ly(gry,x=~Name,y=~Publisher,z=~Global_Sales,color=~Publisher)

plocik <- plot_ly(dane,x=~wydg,y=~dochg)
plocik
plocik2 <-subplot(
plocik %>% add_markers(alpha = 0.2),
plocik %>% add_histogram2d())
plocik2

#plotly maps

plot_ly(df, type='choropleth', locations=df$CODE, z=df$GDP..BILLIONS., text=df$COUNTRY, colorscale="Rainbow")

plot_geo(locationmode = 'USA-states', color = I("red"))

```





